#!/bin/bash
# Script used to monitor jobs and refresco running instances more particularly
# For iridis4 (Southampton)
# by Sebastien Lemaire <sebastien.lemaire@soton.ac.uk>
# license MIT
version="2.1.5"

# default parameters
allparams="-u -t -p -i"
defaultparams="-i"


strg=1
cost=0

maxit=0
memfield=1
runonly=0
project_number=1
cpuhcost=0.05

MemFactor=4
# n MCells => MemFactor*n GB RAM

fileconf="$HOME/.config/rqstat.conf"
# loading configuration file
if [[ -f "$fileconf" ]]
then
    source "$fileconf"
fi

man_sub () {
    echo -e "Usage: rqstat [OPTIONS]
Outputs:
  -i                       Print detailed info about refresco job (default behaviour)
                               A \"\e[31m!\e[0m\" will appear near the \"Iterations\" column if the calculation is not converging
                               The time left will turn red if the runtime specified in the jobfile is not long enough
  -t / --top               Equivalent of slurmtop to summarize cluster load
  -p                       Print info about partitions usage
  -c                       Count the number of core used per user
  -a / --all               Print (almost) everything (equivalent of: rqstat $allparams)

Output tweaking:
  -s                       Don't print the storage needed for simulations (speed up output)
  -r                       Print only running jobs
  --cost                   Print the current and final cost of the job 
  --memory                 Hide the memory/core column
  --maxit                  Print the maximum iteration number possible within the job time limit
  --st                     Sort job list by start time
  --pn                     Don't print the project number in the job name

Tools:
  -d [jobID]               Print the working directory of the specified JobID
  --stop [jobID]           Write a stopfile in the computation working directory to cleanly stop the simulation
  -f / --follow ([time])   Refresh the your job list every [time]s (default being 15s)
  --notif                  Display a desktop notification when a job state changes, needs X-forwarding and -f
  --export-conf            Export a default configuration file in ~/.config/rqstat.conf
  -v / --version           Show version number
  -h / --help              Print this help


  In the main output (-i), all the estimated values (ETA, Time left, Storage, Cost, Max job It) are based on a linear extrapolation of the time the computation took since the start of the job.
  The Mem/core output is an estimation of ReFRESCO memory usage per core based on the cell count of the simulation, the ratio \"n MCells -> $MemFactor*n GB Ram\" is used.
  The --maxit/Max job It output is the maximum number of iteration that can fit within the time limit of the job.
  The cost column is based on a price of $cpuhcost €/CPU h.

  A configuration file can be used to overwrite some default parameters, it must be placed in ~/.config/rqstat.conf, a default configuration file is available via the command --export-conf. 

rqstat is developed under MIT licence: feel free to contribute and give feedback!
Get the latest version from: https://github.com/nanoseb/rsqueue"
}

version_sub () {
    echo "rqstat version $version

rqstat is developed under MIT licence: feel free to contribute and give feedback!
Get the latest version from: https://github.com/nanoseb/rsqueue"

}

export_conf () {

echo "# Configuration file for rqstat
# for power users only ;)
# Note that this file is being sourced, so be carefull with what you put there

# Default output
defaultparams=\"$defaultparams\"

# Parameters used when using -a
allparams=\"$allparams\"

# Prints storage related output (1=true, 0=false)
strg=$strg

# Print job cost column (1=true, 0=false)
cost=$cost

# CPU h cost
cpuhcost=$cpuhcost

# Print "Max job it" column (1=true, 0=false)
maxit=$maxit

# Print Memory/Core column (1=true, 0=false)
memfield=$memfield

# Factor used to compute memory usage
# n MCells => MemFactor*n GB RAM
MemFactor=$MemFactor 

# Print only running jobs (1=true, 0=false)
runonly=$runonly

# Print project number (1=true, 0=false)
project_number=$project_number
" > "$fileconf"

    echo "Configuration file exported to $fileconf"
}



convert_human() {
    awk '{ sum=$1 ; hum[1024**3]="T";hum[1024**2]="G";hum[1024]="M"; for (x=1024**3; x>=1024; x/=1024){ if (sum>=x) { printf "%.1f%s\n",sum/x,hum[x];break } }}' <<<"$1"
}

gen_line() {
    printf "%${1}s\n" "" | sed 's/\ /─/g'
}

main_get_data () {
    
    echo "Directory;Job name;Job-ID;Cores;Iterations;Storage;%;Mem/Core;Cost;Start time;\e[0m;ETA;Time left;Max job It;"

    ETA24hsize=0
    ETAsizetotal=0
    currentsizetotal=0
    nowepoch=$(date +%s)

    while read line;
    do
        [ ! "$line" ] && echo "No job" && strg=0 && continue

        # Gathering of job metadata
        jobstate=$(awk '{print $3}' <<<$line) #
        jobid=$(awk '{print $1}' <<<$line) #
        jobinfo=$(qstat -f $jobid) #
        jobinfoxml=$(qstat -f -x $jobid | xmllint -format -) #

        jobcore=$(awk '{print $4}' <<<$line) #

        jobname=$(grep -m 1 "Job_Name = " <<<"$jobinfo" | awk -F"= " '{print $2}') #

        jobepoch=$(sed 's/</\n</g' <<<"$jobinfoxml" | grep -m 1 "<start_time>" | awk -F">" '{print $2}') #
        jobdate=$(date -d @$jobepoch +%d/%m/%Y) #
        jobtime=$(date -d @$jobepoch +%H:%M) #

        jobout=$(grep Output_Path <<<"$jobinfoxml" | awk -F':|<' '{print $3}') #
        dir=$(grep Variable_List  <<<"$jobinfoxml" | sed 's/,/\n/g' | grep -m 1 ^PBS_O_WORKDIR | awk -F'=' '{print $2}') #
        dirp=$(sed 's/[/\.]*$//' <<<"$dir" | awk -F"/" '{print $NF}')
        # dirp=$(awk -F"/" '{print $NF}' <<<"$(cd "$dir" && pwd)")

        if [ "$project_number" = 1 ]
        then
            jobname_short=$jobname
        else
            jobname_short=$(sed 's/^[^_]*_//' <<<"$jobname")
        fi

        [ -d "$dir" ] || continue
        controlspath="$dir"/controls.xml
        residualspath="$dir"/residuals.dat


        isrefresco="y"
#        [ "$jobstate" = "Running" ] && isrefresco=$(grep -m 1 "^# ReFRESCO " "$jobout" 2> /dev/null)


        if [ "$jobstate" = "Running" ] && [ -e "$controlspath" ] && [ -e "$residualspath" ] && [ "$isrefresco" ]
        then

            controls=$(cat "$controlspath")
            residuals=$( (head; tail) < "$residualspath")

            reportgeneral='<log>'$(tac "$dir"/report_general.xml | sed 's/grid size/grid_size/g' | sed '/^.*<log>$/,$ d' | tac)'</log>'
            nCells=$(xmllint --shell <(echo "$reportgeneral") <<<'cat //log/topology_info/topology_file/nIntCells/total' 2> /dev/null | sed 's/[^0-9]//g;2p' -n)

            if [[ "$nCells" ]]
            then
                mem=$(bc <<<"$nCells * $MemFactor *1.048576/$jobcore") # Memory in K
                mem_s='~'$(convert_human "$mem")
            else
                mem_s=''
            fi

            outerwarn=""
            initialtimestep=0
            unsteady=$(xmllint --shell <(echo "$controls") <<<'cat //controls/timeLoop/unsteady' 2> /dev/null | grep -m 1 true)

            if [ "$unsteady" ]
            then
                currentstep=$(tail -n 1 <(echo "$residuals") | awk '{print $2}' | sed 's/[^0-9]//g')
                maxtimestep=$(xmllint --shell <(echo "$controls") <<<'cat //controls/timeLoop/maxTimesteps' | sed 's/[^0-9]//g;2p' -n)

                initialtimestep=$(xmllint --shell <(echo "$reportgeneral") <<<'cat //log/counters_info/start_time_step' 2> /dev/null| sed 's/[^0-9]//g;2p' -n)

                [ ! "$initialtimestep" ] && initialtimestep=0

                outermax=$(xmllint --shell <(echo "$controls") <<<'cat //controls/outerLoop/maxIteration' | sed 's/[^0-9]//g;2p' -n)
                outercurrent=$(tail -n 1 <(echo "$residuals") | awk '{print $3}')
                [ "$outermax" = "$outercurrent" ] && outerwarn="!"
            else
                currentstep=$(tail -n 1 <(echo "$residuals") | awk '{print $1}' | sed 's/[^0-9]//g')
                maxtimestep=$(xmllint --shell "$controlspath" <<<'cat //controls/outerLoop/maxIteration' | sed 's/[^0-9]//g;2p' -n)
            fi

            initialtimestepf=$(head -n 3 <(echo "$residuals") | sed '3!d' | awk '{print $2}')
            [ -z "$initialtimestepf" ] && initialtimestepf=$initialtimestep

            [ -z "$currentstep" ] && currentstep=$(bc <<<"$initialtimestep +1")
            [ "$currentstep" = "$initialtimestepf" ] && currentstep=$(bc <<<"$initialtimestepf +1")


            jobtimeremaining=$(grep Remaining  <<<"$jobinfoxml" | awk -F'>|<' '{print $3}')
            startepoch=$(grep start_time  <<<"$jobinfoxml" | awk -F'>|<' '{print $3}')
            jobtimelimit=$(bc <<<"$nowepoch -$startepoch + $jobtimeremaining")
            ETAepoch=$(bc <<<"$nowepoch + ($maxtimestep - $currentstep)*($nowepoch - $startepoch)/($currentstep-$initialtimestep)")
            ETAdate=$(date -d @$ETAepoch +%d/%m/%Y\ %H:%M)
            ETAsl=$((ETAepoch - nowepoch))
#            jobdate=$(date -d @$startepoch +%d/%m/%Y)
#            jobtime=$(date -d @$startepoch +%H:%M)

            if [ $((ETAsl - 90000 )) -lt 0 ]
            then
                ETAtime=$(echo 0$(bc <<<"$ETAsl/3600"):0$(bc <<<"($ETAsl%3600)/60") | sed 's/:0\(..\)$/:\1/;s/^0\(..\):/\1:/')
            else
                ETAtimes=$((ETAsl -90000))
                ETAday=$(date -d @$ETAtimes +%j)
                if [ "$ETAday" -gt 50 ]
                then
                    ETAtime=$(echo $(bc <<<"$ETAday/30") months $(bc <<<"$ETAday%30") days | sed 's/\ 0\ ....$//;s/\ 1\ ..../\ 1\ day/;s/^1\ ....../1\ month/')
                else
                    ETAtime=$(echo $ETAday days $(date -d @$ETAtimes +%H:%M) | sed 's/^0*//;s/^\ ....//;s/^1\ ..../1\ day/')
                fi
            fi

            colortime="\e[0m"
            [ "$ETAepoch" ] && [[ "$((nowepoch + jobtimeremaining))" -lt "$ETAepoch" ]] && colortime='\e[31m'

            percent=$(bc <<<"100*($currentstep-$initialtimestepf)/($maxtimestep-$initialtimestepf)")


            costETA=$(bc <<<"$cpuhcost*$jobcore*($ETAepoch-$startepoch)/3600")
            costnow=$(bc <<<"$cpuhcost*$jobcore*($nowepoch-$startepoch)/3600")

            maxIteration=$(bc <<<"($currentstep-$initialtimestep)*($jobtimelimit)/($nowepoch-$startepoch) + $initialtimestep")
            maxitString="$maxIteration"

            nowsizeh=""
            ETAsizeh=""
            if [ "$strg" = "1" ]
            then
                nowsize=$(du -s "$dir" | awk '{print $1}')
                ETAsize=$(bc <<<"($maxtimestep - $currentstep)*($nowsize)/($currentstep-$initialtimestepf)")
                ETAsizeh=$(convert_human $(bc <<<"$ETAsize+$nowsize"))
                nowsizeh=$(convert_human $nowsize)
                ETAsizetotal=$((nowsize + ETAsize + ETAsizetotal))
                currentsizetotal=$((nowsize + currentsizetotal))
                if [[ "$((10#$ETAday))" -ge 1 ]]
                then
                    ETA24hsize=$(bc <<<"$ETA24hsize + 86400*$nowsize*($currentstep-$initialtimestep)/(($currentstep-$initialtimestepf)*($nowepoch - $startepoch))")
                else
                    ETA24hsize=$((ETA24hsize + ETAsize))
                fi
            fi


            nprocs=$(xmllint --shell <(echo "$reportgeneral") <<<'cat //log/nprocs' 2> /dev/null | sed 's/[^0-9]//g;2p' -n)
            [[ "$nprocs" ]] && [[ "$nprocs" != "$jobcore" ]] && jobcore="$nprocs/$jobcore"
            echo "${dirp:0:15};${jobname_short:0:15};$jobid;$jobcore;$currentstep/$maxtimestep $outerwarn;$nowsizeh/$ETAsizeh;$percent%;$mem_s;$costnow/$costETA €;$jobdate $jobtime;$colortime;$ETAdate;$ETAtime;$maxitString;"

        else
            refresco=''
            [ ! "$isrefresco" ] && refresco="NO ReFRESCO"
            colorpd=""
            [ "$jobstate" = "Idle" ] && colorpd="\e[2m"
            [ "$jobstate" = "Idle" ] && [ -f "$dir"/stopfile ] && refresco="$refresco"'/!\ '"stopfile present"

            if [ "$runonly" = "0" ] || [ "$jobstate" = "Running" ]
            then
                echo "${dirp:0:15};${jobname_short:0:15};$jobid;$jobcore;$jobstate;;;;;$jobdate $jobtime;\e[31m;$refresco;"
            fi
        fi
    done <<<"$(showq -u $USER | grep $USER)"

    [ $strg = 1 ] && storage_sub
}

main_sub () {

    data=$(main_get_data)
    storage=$(sed -n '/^$/,$p' <<<"$data")
    data=$(sed '/^$/,+3d' <<<"$data")

    [ "$debug" ] && data="$data"$'\n'"$(seq 15 | tr "\n" ";")"

    # remove maxit
    [ "$maxit" != 1 ] && data=$(sed 's/[^;]*;//14' <<<"$data")

    # remove cost
    [ "$cost" != 1 ] && data=$(sed 's/[^;]*;//9' <<<"$data")

    # remove memory 
    [ "$memfield" != 1 ] && data=$(sed 's/[^;]*;//8' <<<"$data")

    # remove storage
    [ "$strg" != 1 ] && data=$(sed 's/[^;]*;//6' <<<"$data")


    echo -e "$data" |\
        sed 's/;;/; ;/g;s/;;/; ;/g' |\
        column -t -s ';' |\
        sed -r 's/^(.*)Idle(.*)$/\x1b[2m\1Idle\2/;s/$/\x1b[0m/' |\
        sed -r 's/^(.*)Deferred(.*)$/\x1b[2m\1Deferred\2/;s/$/\x1b[0m/' |\
        sed 's/\(.\!.\)/\x1b[31m\1\x1b[0m/'

    echo "$storage"
}


storage_sub () {
    echo
    echo Total disk space needed: $(convert_human $ETAsizetotal)
    # [ "$marclus" = 4 ] && echo Current disk usage: $(convert_human $currentsizetotal)
    echo Disk usage growth rate: $(convert_human $ETA24hsize)/day

}


count_sub () {
    echo -e "\e[34m\e[4mUsed CPUs per user:\e[0m"
    list=$(showq -r | tail -n+5| head -n-6)

    users_c=$(awk '{print $7}' <<<"$list" | sort | uniq)
    used_core=$(awk '{s+=$10} END {print s}' <<<"$list")
    nb_user=$(wc -l <<<"$users_c")
    avg=$(bc <<<"$used_core / $nb_user")

    while read user
    do
        nb=$(grep \ $user\  <<<"$list" | awk '{s+=$10} END {print s}')
        if [[ "$nb" -gt "$avg" ]]
        then
            echo -e "$user: \e[31m$nb\e[0m"
        else
            echo -e "$user: $nb"
        fi
    done <<<"$users_c" | column -t
}


top_sub () {

    list=$(showq -r | tail -n+5| head -n-6)
    users_t=$(awk '{print $7}' <<<"$list" | sort -u)
    echo "User Nb_Jobs State Nb_CPU Partitions"
    while read user
    do
        userlist=$(grep \ $user\  <<<"$list") 
        nbjob=$(wc -l <<<"$userlist")
        core=$(awk '{s+=$10} END {print s}' <<<"$userlist")
        partition=$(awk '{print $6}' <<<"$userlist" | sort -u | tr '\n' ',' | sed 's/,$//')
        echo $user $nbjob running $core $partition

    done <<<"$users_t" | sort -n -k 4 -r

    if [ "$runonly" = "0" ]
    then
        list=$(showq -i | tail -n+5| head -n-6)
        users_t=$(awk '{print $5}' <<<"$list" | sort -u)
        while read user
        do
            userlist=$(grep \ $user\  <<<"$list") 
            nbjob=$(wc -l <<<"$userlist")
            core=$(awk '{s+=$7} END {print s}' <<<"$userlist")
            partition=$(awk '{print $4}' <<<"$userlist" | sort -u | tr '\n' ',' | sed 's/,$//')
            echo "$user $nbjob pending $core $partition"

        done <<<"$users_t" | sort -n -k 4 -r
    fi

}


wdir_sub () {
    if [ -z $jobid_d ]
    then
        jobid_d=$(showq -u $USER | grep $USER | head -n 1 | awk '{print $1}')
        [ -z $jobid_d ] && echo "No jobID" && exit 1
    fi
    dir=$(qstat -f -x $jobid_d | xmllint -format - | grep Variable_List | sed 's/,/\n/g' | grep -m 1 ^PBS_O_WORKDIR | awk -F'=' '{print $2}') 
    [ -z "$dir" ] && echo . && exit 1
    echo $dir
}


#userl_sub () {
#    arg=''
#    [ "$users" ] && arg="-u $users"
#    [ "$runonly" = "1" ] && arg="$arg -t R"
#    template="%8i %5Q %9P %14u %30j %8T %18S %.12l %.12L %.4C"
#    [ "$nodelist" ] && template="$template %R"
#    result=$(squeue $arg -S $sort -o "$template" | \
#        sed -r 's/([0-9])T([0-9])/\1\ \2/;s/:[0-9]*\ /\ \ \ \ /;s/^(.*)PENDING(.*)$/\x1b[2m\1PENDING\2\x1b[0m/')
#    if [ "$project_number" = 1 ]
#    then
#        echo -e "$result"
#    else
#        echo -e "$result" | sed -r 's/P[0-9]{5}\.[0-9]{3}//;s/\ _/\ \ /;s/NAME(\ ){11}/\ NAME/'
#    fi
#}


partition_sub () {
    echo "Type,Total,Used,Available,Usage"
    showq -r | grep "%" | sed ':a;N;$!ba;s/\n/ /g' | sed 's/(//g;s/)//g' | \
        awk '{printf "%s,%d,%d,%d,%d %\n%s,%d,%d,%d,%d %\n",
        "CPU", $6, $4, $6-$4, $13, "Node", $16, $14, $16-$14, $19}'
}



stopcomputation_sub () {
    [ -z $jobid_d ] && echo "Error: no jobID given" && exit 1
    state=$(showq -u $USER | grep $jobid_d | awk '{print $3}')
    if [ "$state" == "Running" ]
    then
        dir=$(qstat -f -x $jobid_d | xmllint -format - | grep Variable_List | sed 's/,/\n/g' | grep -m 1 ^PBS_O_WORKDIR | awk -F'=' '{print $2}') 
        [ -z "$dir" ] && exit 1

        touch "$dir"/stopfile && echo stopfile written to "$dir"
    else
        echo "Job not running, launching 'scancel $jobid_d'"
        scancel "$jobid_d"
    fi
}


display-notif () {
    pendingJobs=$(squeue -h -u $USER -o "%T" | grep PENDING | wc -l)
    runningJobs=$(squeue -h -u $USER -o "%T" | grep RUNNING | wc -l)

    [[ -z "$pendingJobsOld" ]] && pendingJobsOld=$pendingJobs
    [[ -z "$runningJobsOld" ]] && runningJobsOld=$runningJobs

    if [[ "$runningJobsOld" != "$runningJobs" ]] || [[ "$pendingJobsOld" != "$pendingJobs" ]]
    then
        diffrunning=$((runningJobs - runningJobsOld))
        diffpending=$((pendingJobs - pendingJobsOld))
        [[ ${diffrunning:0:1} != '-' ]] && diffrunning="+$diffrunning"
        [[ ${diffpending:0:1} != '-' ]] && diffpending="+$diffpending"
        pendingJobsOld="$pendingJobs"
        runningJobsOld="$runningJobs"

        notify-send "rqstat on $HOSTNAME" "$runningJobs running jobs ($diffrunning)\n$pendingJobs pending jobs ($diffpending)"
    fi
}

printWHeader () {
    sub="$1"
    size=$(wc -L <<<"$sub")
    size=$(sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g" <<<"$sub" | wc -L)
    echo "$sub" | sed "2i$(gen_line $size)"
}

erase () {
    for i in $(seq $1)
    do
        tput cuu1
        echo -en "\033[2K"
        printf "%${COLUMNS}s" ""
        echo -en "\033[2K"
    done
}

sort="-T,u,i"


while [[ $# -gt 0 ]]
do
    case $1 in
        -i)
            params="$params -i"
            shift
            ;;
        -s)
            strg=0
            shift
            ;;
        -r)
            runonly=1
            shift
            ;;
        -c)
            params="$params -c"
            shift
            ;;
        -d)
            shift
            jobid_d="$1"
            wdir_sub
            exit 0
            ;;
        -t|--top)
            params="$params -t"
            shift
            ;;
        --pn)
            project_number=0
            shift
            ;;
        -a|--all)
            params="$params -a"
            shift
            ;;
        --st)
            sort="S,-Q"
            shift
            ;;
        -p)
            params="$params -p"
            shift
            ;;
        --maxit)
            maxit=1
            shift
            ;;
        --cost)
            cost=1
            shift
            ;;
        --memory)
            memfield=0
            shift
            ;;
        -f|--follow)
            if [ -z "$2" ] || [ "${2:0:1}" = "-" ]
            then
                refresh_time="15"
            else
                shift
                refresh_time="$1"
            fi

            follow="y"
            shift
            ;;
        --notif)
            if [ -n "$DISPLAY" ]
            then
                notif=1
            else
                notif=0
                echo "WARNING: Notification display not possible, you need ssh X-forwarding"
            fi
            shift
            ;;
        --stop)
            shift
            jobid_d="$1"
            stopcomputation_sub
            exit 0
            ;;
        --export-conf)
            export_conf 
            exit 0
            ;;
        -h|--help)
            man_sub
            exit 0
            ;;
        -v|--version)
            version_sub
            exit 0
            ;;
        --debug)
            debug=1
            shift
            ;;
        *)
            echo "Unknown argument: $1"
            man_sub
            exit 1
            ;;
    esac
done


if [ -z "$params" ]
then
    params=$defaultparams
fi

if [ "$(grep '\-a' <<<"$params")" ]
then
    params=$allparams
fi

for param in $params
do
    case $param in
        -i) [[ "$follow" ]] || printWHeader "$(main_sub)"
            ;;
        -c) count_sub
            ;;
        -d) wdir_sub
            ;;
        -t) printWHeader "$(top_sub  | column -t  | sed -r 's/^(.*)pending(.*)$/\x1b[2m\1pending\2\x1b[0m/' | sed 's/_/ /g')"
            ;;
        -p) printWHeader "$(partition_sub | column -t -s ',' | sed -r 's/([0-9]+)/\x1b[32m\1\x1b[0m/3')"
            ;;
    esac

    echo
done

if [[ "$follow" ]] 
then
    main_nb_line=0
    pendingJobsOld=""
    runningJobsOld=""

    # remove storage when using -f
    strg=0

    while true;
    do
        var=$(printWHeader "$(main_sub)")
        erase $main_nb_line
        echo "$var"
        main_nb_line=$(wc -l <<<"$var")

        [ "$notif" ] && display-notif
        sleep "$refresh_time"
    done
fi

# vim: ai ts=4 sw=4 et sts=4 ft=sh
